# Generated by Django 3.0 on 2020-01-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_member_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
