# Generated by Django 3.0 on 2020-01-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_member_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
