# Generated by Django 3.0 on 2020-01-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_member_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='fitness_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=6),
        ),
    ]
