# Generated by Django 3.0 on 2020-01-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_member_fitness_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.CharField(default='Not given', max_length=255),
        ),
    ]
