# Generated by Django 3.0 on 2020-01-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_session_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(default='Please call 0300 45 45 for more info'),
        ),
    ]
