# Generated by Django 3.0 on 2020-01-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_session_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=6),
        ),
    ]
