# Generated by Django 3.0 on 2020-01-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_session_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='capacity',
            field=models.IntegerField(default=15),
        ),
    ]
